export const ColumnsNameExportBookingAdmin = [
  'STT',
  'THÔNG TIN XỬ LÝ',
  'NGÀY BOOKING',
  'NGÀY YÊU CẦU LẤY HÀNG',
  'AWB NO',
  'CWB NO',
  'MÃ BILL ĐỐI TÁC',
  'DỊCH VỤ ĐỐI TÁC',
  'NHÀ CUNG CẤP',
  'MÃ BƯU TRONG NƯỚC',
  'DỊCH VỤ ĐỐI TÁC TRONG NƯỚC',
  'NHÀ CUNG CẤP TRONG NƯỚC',
  'NƯỚC GỬI',
  'NƯỚC ĐẾN',
  'DỊCH VỤ',
  'LOẠI HÀNG HÓA',
  'CÓ/KHÔNG INVOICE',
  'HÌNH THỨC THANH TOÁN',
  'SỐ KIỆN',
  'TRỌNG LƯỢNG THỰC',
  'TRỌNG LƯỢNG CỒNG KỀNH',
  'Chiều dài',
  'Chiều rộng',
  'Chiều cao',
  'MÃ KHÁCH HÀNG',
  'CÔNG TY GỬI (TIẾNG ANH)',
  'ĐỊA CHỈ GỬI TIẾNG ANH 1',
  'ĐỊA CHỈ GỬI TIẾNG ANH 2',
  'ĐỊA CHỈ GỬI TIẾNG ANH 3',
  'TỈNH/THÀNH PHỐ GỬI',
  'THÀNH PHỐ/QUẬN/HUYỆN',
  'MÃ BƯU CHÍNH (NƠI GỬI)',
  'TÊN NGƯỜI GỬI',
  'SỐ ĐIỆN THOẠI NGƯỜI GỬI',
  'TÊN CÔNG TY NHẬN',
  'ĐỊA CHỈ NHẬN 1',
  'ĐỊA CHỈ NHẬN 2',
  'ĐỊA CHỈ NHẬN 3',
  'TỈNH/THÀNH PHỐ NHẬN',
  'THÀNH PHỐ/QUẬN/HUYỆN',
  'MÃ BƯU CHÍNH (NƠI NHẬN)',
  'TÊN NGƯỜI NHẬN',
  'SỐ ĐIỆN THOẠI NGƯỜI NHẬN',
  'NỘI DUNG HÀNG HÓA',
  'MẶT HÀNH VẬN CHUYỂN (TIẾNG ANH)',
  'ĐIỀU KIỆN GIAO HÀNG',
  'ĐƠN VỊ TÍNH',
  'THỜI GIAN XÁC NHẬN LẤY HÀNG',
  'THỜI GIAN XUẤT RA KHỎI CÔNG TY',
  'THỜI GIAN PHÁT HÀNG THÀNH CÔNG',
  'TRẠNG THÁI ĐƠN HÀNG',
  'GHI CHÚ',
  'Dịch vụ chuyên tuyến/ Dịch vụ khác',
  'Dịch vụ DHL',
  'Dịch vụ Fedex',
  'Dịch vụ UPS',
  'LOẠI TIỀN TỆ',
  'ĐƠN VỊ',
  'TỔNG SỐ LƯỢNG',
  'ĐƠN GIÁ',
  'THÀNH TIỀN',
  'MÃ BILL ĐỐI TÁC TRACKING',
];

export const columnsNameExportBookingClient = [
  [
    'STT',
    'TÌNH TRẠNG',
    'NGÀY BOOKING',
    'SỐ THAM CHIẾU',
    'CWB NO',
    'LOẠI GỬI',
    'NƯỚC GỬI',
    'NƯỚC ĐẾN',
    'DỊCH VỤ',
    'SỐ KIỆN',
    'TRỌNG LƯỢNG THỰC',
    'TRỌNG LƯỢNG CỒNG KỀNH',
    'CÔNG TY GỬI (TIẾNG ANH)',
    'ĐỊA CHỈ GỬI (TIẾNG ANH)',
    'THÀNH PHỐ GỬI',
    'MÃ BƯU CHÍNH (TP GỬI)',
    'TÊN NGƯỜI GỬI',
    'SỐ ĐIỆN THOẠI NGƯỜI GỬI',
    'TÊN CÔNG TY NHẬN',
    'ĐỊA CHỈ NHẬN',
    'THÀNH PHỐ NHẬN',
    'MÃ BƯU CHÍNH (TP NHẬN)',
    'TÊN NGƯỜI NHẬN',
    'SỐ ĐIỆN THOẠI NGƯỜI NHẬN',
    'NỘI DUNG HÀNG HÓA',
    'ĐIỀU KIỆN GIAO HÀNG',
    'ĐƠN VỊ TÍNH',
  ],
];
