version: "3.8"

services:
  backend-mh:
    build: ./MH-api
    container_name: backend-mh
    environment:
      DATABASE_URL: postgresql://dev:devdsea123@103.216.115.200:5432/mhcom_db
      NODE_ENV: local
    volumes:
      - mh_uploads:/usr/src/app/uploads
    networks:
      # - proxy
      - mh-internal
    restart: unless-stopped
    ports:
      - "4000:3000"
    # Backend is not publicly exposed; only accessible via internal network
    # No Traefik labels here to keep it internal

  frontend-mh:
    build:
      context: ./MH
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_HOST=http://backend-mh:3000
        - NODE_ENV=production
    container_name: frontend-mh
    depends_on:
      - backend-mh
    
    environment:
      NEXT_PUBLIC_API_HOST: http://localhost:4000
      NODE_ENV: production
    labels:
        - "traefik.enable=true"

  # HTTP
        - "traefik.http.routers.mhcom-frontend.rule=Host(`mhgreatsun.com`)"
        - "traefik.http.routers.mhcom-frontend.entrypoints=web"
        - "traefik.http.middlewares.mhcom-frontend-https.redirectscheme.scheme=https"

  # HTTPS
        - "traefik.http.routers.mhcom-frontend-secure.rule=Host(`mhgreatsun.com`)"
        - "traefik.http.routers.mhcom-frontend-secure.entrypoints=websecure"
        - "traefik.http.routers.mhcom-frontend-secure.tls.certresolver=le"
        - "traefik.http.routers.mhcom-frontend-secure.service=mhcom-frontend"

  # Service
        - "traefik.http.services.mhcom-frontend.loadbalancer.server.port=3000"
    networks:
      - proxy
      - mh-internal
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mh_uploads:
    driver: local

networks:
  proxy:
    external: true
  mh-internal:
    driver: bridge
