version: "3.8"

services:
  be:
    build: 
      context: ./be
      dockerfile: Dockerfile
    container_name: mhgs_be
    expose:
      - "8000"
    volumes:
      - ./data:/home/mhgs_log_be/data
    environment:
      DB_NAME: mhgs_clone
    networks:
      - proxy
      - app1-internal

  begp:
    build: 
      context: ./be
      dockerfile: Dockerfile.gp
    container_name: gp_be
    expose:
      - "8668"
    volumes:
      - ./datagp:/home/mhgs_log_be/data
    environment:
      DB_NAME: gp_clone
    networks:
      - proxy
      - app1-internal

  ocr:
    build: ./ocr
    container_name: mhgs_ocr
    volumes:
      - pip-cache:/pip-cache
    ports:
      - "9000:9000"
    networks:
      - app1-internal

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.web-a
    container_name: mhgs_web
    depends_on:
      - be
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1-frontend.rule=Host(`mhgreatsun.vn`)"
      - "traefik.http.routers.app1-frontend.entrypoints=websecure"
      - "traefik.http.routers.app1-frontend.tls.certresolver=le"
      - "traefik.http.services.app1-frontend.loadbalancer.server.port=80"
    networks:
      - proxy
      - app1-internal

  webgp:
    build: 
      context: ./gp_web
      dockerfile: Dockerfile.web-b
    container_name: gp_web
    ports:
      - "8081:80"
    depends_on:
      - begp
    networks:
      - app1-internal

  chatbot:
    build: ./chatbot
    container_name: mhgs_chatbot
    ports:
      - "8100:8100"
    depends_on:
      - mongo  
    networks:
      - app1-internal
      
  mongo:
    image: mongo:4.4
    container_name: mhgs_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    networks:
      - app1-internal

  reader:
    build: ./content-reader
    container_name: mhgs_chatbot_content_reader
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    networks:
      - app1-internal

volumes:
  pip-cache:
    driver: local

networks:
  proxy:
    external: true
  app1-internal:
    driver: bridge