import { type ShippingRate } from './types';

export const FAKE_SHIPPING_RATES: ShippingRate[] = [
  {
    id: '1',
    routeCode: 'TR-HCM-HN',
    origin: 'Hồ Chí Minh',
    destination: 'Hà Nội',
    vehicleType: 'Xe tải 5 tấn',
    unit: 'Chuyến',
    price: 12000000,
    effectiveDate: '2024-01-01',
    status: 'Đang áp dụng',
  },
  {
    id: '2',
    routeCode: 'TR-HCM-DN',
    origin: 'Hồ Chí Minh',
    destination: 'Đà Nẵng',
    vehicleType: 'Xe tải 2.5 tấn',
    unit: 'Chuyến',
    price: 7500000,
    effectiveDate: '2024-01-01',
    status: 'Đang áp dụng',
  },
  {
    id: '3',
    routeCode: 'TR-HN-HP',
    origin: 'Hà Nội',
    destination: 'Hải Phòng',
    vehicleType: 'Container 20ft',
    unit: 'Container',
    price: 4200000,
    effectiveDate: '2024-02-01',
    status: 'Đang áp dụng',
  },
  {
    id: '4',
    routeCode: 'TR-HCM-CT',
    origin: 'Hồ Chí Minh',
    destination: 'Cần Thơ',
    vehicleType: 'Xe tải 1.25 tấn',
    unit: 'Chuyến',
    price: 3200000,
    effectiveDate: '2023-11-01',
    status: 'Hết hiệu lực',
  },
  {
    id: '5',
    routeCode: 'TR-DN-HCM',
    origin: 'Đà Nẵng',
    destination: 'Hồ Chí Minh',
    vehicleType: 'Hàng lẻ (kg)',
    unit: 'Kg',
    price: 4500,
    effectiveDate: '2024-03-01',
    status: 'Đang áp dụng',
  },
  {
    id: '6',
    routeCode: 'TR-HN-DN',
    origin: 'Hà Nội',
    destination: 'Đà Nẵng',
    vehicleType: 'Xe tải 5 tấn',
    unit: 'Chuyến',
    price: 9800000,
    effectiveDate: '2024-04-01',
    status: 'Nháp',
  },
];
