export const connectBillColumnName = [
  'ID',
  'DATE',
  'MAWB',
  'HAWB',
  'Type',
  'Tracking No',
  'Reference number',
  'Account',
  'Shipper',
  'Shipper Company',
  'Shipper Add 1',
  'Shipper Add 2',
  'Shipper Add 3',
  'Shipper district',
  'Shipper province',
  'Shipper Postal Code',
  'Shipper Tel',
  'Shipper Country',
  'Other Tracking',
  'Cnee',
  'Cnee Company',
  'Cnee Add 1',
  'Cnee Add 2',
  'Cnee Add 3',
  'Cnee district',
  'Cnee province',
  'Cnee Code',
  'Cnee Postal Code',
  'Cnee Tel',
  'Cnee Country',
  'CW',
  'NW',
  'GW',
  'Box Number',
  'Length',
  'Width',
  'Height',
  'Commodity',
  'Export form',
  'Transportation',
  'Service',
  'Connection Service Request',
  'Connection service',
  'Connection partner',
  'Postal code of domestic service connection partner in Vietnam ',
  'Domestic partner services',
  'Domestic Supplier',
  'Overseas Partner Postal Code',
  'Overseas partner services',
  'Foreign Supplier',
  'Type of payment',
  'Delivery conditions',
  'Note',
  'Mã bill đối tác tracking',
  'Dịch vụ chuyên tuyến/ Dịch vụ khác',
  'Dịch vụ DHL',
  'Dịch vụ Fedex',
  'Dịch vụ UPS',
  'Nhân viên kinh doanh',
  'Nhân viên pick up (Nhận hàng)',
  'Nhân viên pick up (Check in)',
  'Nhân viên vận hành (Check out)',
  'Nhân viên vận hành (Xuất Manifest)'
];

export const connectBillOPColumnName = [
  'ID',
  'DATE',
  'MAWB',
  'HAWB',
  'Type',
  'Classify', // Nhóm bưu (Bưu gốc/Bưu phân chia)
  'Tracking No',
  'Separate parcels', // Mã bill đối tác bill tách
  'Reference number',
  'Account',
  'Shipper',
  'Shipper Company',
  'Shipper Add 1',
  'Shipper Add 2',
  'Shipper Add 3',
  'Shipper district',
  'Shipper province',
  'Shipper Postal Code',
  'Shipper Tel',
  'Shipper Country',
  'Other Tracking',
  'Cnee',
  'Cnee Company',
  'Cnee Add 1',
  'Cnee Add 2',
  'Cnee Add 3',
  'Cnee district',
  'Cnee province',
  'Cnee Code',
  'Cnee Postal Code',
  'Cnee Tel',
  'Cnee Country',
  'CW',
  'NW',
  'GW',
  'Box Number',
  'Length',
  'Width',
  'Height',
  'Commodity',
  'Export form',
  'Transportation',
  'Service',
  'Connection Service Request',
  'Connection service',
  'Connection partner',
  'Postal code of domestic service connection partner in Vietnam ',
  'Domestic partner services',
  'Domestic Supplier',
  'Overseas Partner Postal Code',
  'Overseas partner services',
  'Foreign Supplier',
  'Type of payment',
  'Delivery conditions',
  'Note',
  'Mã bill đối tác tracking',
  'Dịch vụ chuyên tuyến/ Dịch vụ khác',
  'Dịch vụ DHL',
  'Dịch vụ Fedex',
  'Dịch vụ UPS',
  'Nhân viên kinh doanh',
  'Nhân viên pick up (Nhận hàng)',
  'Nhân viên pick up (Check in)',
  'Nhân viên vận hành (Check out)',
  'Nhân viên vận hành (Xuất Manifest)'
];

export const connectBillMultiParcelColumnName = [
  'ID',
  'DATE',
  'MAWB',
  'HAWB',
  'Type',
  'Tracking No',
  'Reference number',
  'Account',
  'Shipper',
  'Shipper Company',
  'Shipper Add 1',
  'Shipper Add 2',
  'Shipper Add 3',
  'Shipper district',
  'Shipper province',
  'Shipper Postal Code',
  'Shipper Tel',
  'Shipper Country',
  'Other Tracking',
  'Cnee',
  'Cnee Company',
  'Cnee Add 1',
  'Cnee Add 2',
  'Cnee Add 3',
  'Cnee district',
  'Cnee province',
  'Cnee Code',
  'Cnee Postal Code',
  'Cnee Tel',
  'Cnee Country',
  'CW',
  'NW',
  'GW',
  'Box Number',
  'Length',
  'Width',
  'Height',
  'Box',
  'CW-Box',
  'NW-Box',
  'GW-Box',
  'Commodity',
  'Export form',
  'Transportation',
  'Service',
  'Connection Service Request',
  'Connection service',
  'Connection partner',
  'Postal code of domestic service connection partner in Vietnam ',
  'Domestic partner services',
  'Domestic Supplier',
  'Overseas Partner Postal Code',
  'Overseas partner services',
  'Foreign Supplier',
  'Type of payment',
  'Delivery conditions',
  'Note',
  'Mã bill đối tác tracking',
  'Dịch vụ chuyên tuyến/ Dịch vụ khác',
  'Dịch vụ DHL',
  'Dịch vụ Fedex',
  'Dịch vụ UPS',
  'Nhân viên kinh doanh',
  'Nhân viên pick up (Nhận hàng)',
  'Nhân viên pick up (Check in)',
  'Nhân viên vận hành (Check out)',
  'Nhân viên vận hành (Xuất Manifest)'
];

export const connectBillMultiParcelOPColumnName = [
  'ID',
  'DATE',
  'MAWB',
  'HAWB',
  'Type',
  'Classify', // Nhóm bưu (Bưu gốc/Bưu phân chia)
  'Tracking No',
  'Separate parcels', // Mã bill đối tác bill tách
  'Reference number',
  'Account',
  'Shipper',
  'Shipper Company',
  'Shipper Add 1',
  'Shipper Add 2',
  'Shipper Add 3',
  'Shipper district',
  'Shipper province',
  'Shipper Postal Code',
  'Shipper Tel',
  'Shipper Country',
  'Other Tracking',
  'Cnee',
  'Cnee Company',
  'Cnee Add 1',
  'Cnee Add 2',
  'Cnee Add 3',
  'Cnee district',
  'Cnee province',
  'Cnee Code',
  'Cnee Postal Code',
  'Cnee Tel',
  'Cnee Country',
  'CW',
  'NW',
  'GW',
  'Box Number',
  'Length',
  'Width',
  'Height',
  'Box',
  'CW-Box',
  'NW-Box',
  'GW-Box',
  'Commodity',
  'Export form',
  'Transportation',
  'Service',
  'Connection Service Request',
  'Connection service',
  'Connection partner',
  'Postal code of domestic service connection partner in Vietnam ',
  'Domestic partner services',
  'Domestic Supplier',
  'Overseas Partner Postal Code',
  'Overseas partner services',
  'Foreign Supplier',
  'Type of payment',
  'Delivery conditions',
  'Note',
  'Mã bill đối tác tracking',
  'Dịch vụ chuyên tuyến/ Dịch vụ khác',
  'Dịch vụ DHL',
  'Dịch vụ Fedex',
  'Dịch vụ UPS',
  'Nhân viên kinh doanh',
  'Nhân viên pick up (Nhận hàng)',
  'Nhân viên pick up (Check in)',
  'Nhân viên vận hành (Check out)',
  'Nhân viên vận hành (Xuất Manifest)'
];

export const PODReportColumnName = [
  'STT',
  'Ngày xuất ra khỏi công ty',
  'Tổng số bưu xuất',
  'Tổng số bưu đã phát thành công',
  'Tỷ lệ phát thành công',
  'Số bưu phát ngày 1',
  'Tỷ lệ phát Ngày 1',
  'Số bưu phát ngày 2',
  'Tỷ lệ phát Ngày 2',
  'Số bưu phát ngày 3',
  'Tỷ lệ phát Ngày 3',
  'Số bưu phát ngày 4',
  'Tỷ lệ phát Ngày 4',
  'Số bưu phát ngày 5',
  'Tỷ lệ phát Ngày 5',
  'Số bưu phát ngày 6',
  'Tỷ lệ phát Ngày 6',
  'Số bưu phát ngày 7',
  'Tỷ lệ phát Ngày 7',
  'Số bưu phát ngày 8',
  'Tỷ lệ phát Ngày 8',
  'Số bưu phát ngày 9',
  'Tỷ lệ phát Ngày 9',
  'Số bưu phát ngày 10',
  'Tỷ lệ phát Ngày 10',
  'Số bưu phát trên 10 ngày',
  'Tỷ lệ phát trên 10 ngày',
];

export const OrderRemainingReportColumnName = [
  'STT',
  'Số bưu ACF',
  'Số bưu đối tác',
  'Đối tác kết nối',
  'Mã khách hàng',
  'Tên khách hàng',
  'Ngày pick up nhận vào',
  'Ngày xuất ra khỏi công ty',
  'Số ngày tồn chưa phát kể từ khi xuất ra',
  'Note tình trạng và xử lý đơn hàng',
];
