export const columnNameExportManifestYamato = [
  'Ship Date',
  'Handling Type',
  'Shipment Type',
  'Shipper Name',
  'Shipper Add 1',
  'Shipper Add 2',
  'Shipper Add 3',
  'Shipper Add 4',
  'Shipper Postal Code',
  'Shipper Phone',
  'Package ID',
  'Tracking No',
  'Reference No',
  'Cnee Company',
  'Cnee Add 1',
  'Cnee Add 2',
  'Cnee Add 3',
  'Cnee Add 4',
  'Cnee Tel',
  'Cnee Postal Code',
  'Cnee Name in Katakana',
  'GW',
  'Unit of weight',
  'Payment term',
  'Freight Charge',
  'Item code',
  'Item name',
  'Origin of Country',
  'Qty',
  'UOM',
  'Unit Price',
  'Invoice Cur',
  'Length',
  'Width',
  'Height',
  'Length Unit',
  'Insurance',
  'Consignee Japan name',
  'Consignee code',
  'Registered company name',
  'Address',
];
