export const QUERY_BOOKING = {
  GET_BOOKING: 'GET_BOOKING',
  CREATE_BOOKING: 'CREATE_BOOKING',
};

export const QUERY_BOOKING_ADDRESS = {
  GET_BOOKING_ADDRESS: 'GET_BOOKING_ADDRESS',
  CREATE_BOOKING_ADDRESS: 'CREATE_BOOKING_ADDRESS',
};
