export const QUERY_POST = {
  GET_OPTIONS_HOMEPAGE: 'GET_OPTIONS_HOMEPAGE',
  GET_DETAILS_POST: 'GET_DETAILS_POST',
  GET_POSTS_SIMILAR: 'GET_POSTS_SIMILAR',
  GET_DETAIL_CATEGORY: 'GET_DETAIL_CATEGORY',
  GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
  GET_LIST_CATEGORY_CREATE_POST: 'GET_LIST_CATEGORY_CREATE_POST',
  GET_LIST_POST: 'GET_LIST_POST',
  CREATE_POST: 'CREATE_POST',
  CREATE_HOMEPAGE: 'CREATE_HOMEPAGE',
  CREATE_CATEGORY_POST: 'CREATE_CATEGORY_POST',
};
