export const ExportPriceListColumnName = [
  [
    'Loại khách hàng',
    'Mã khách hàng',
    'Tên khách hàng',
    'Thời gian cập nhật',
    'Dịch vụ yêu cầu',
    'Doanh thu tiềm năng từ (triệu đồng)',
    'Doanh thu tiềm năng đến (triệu đồng)',
    'Bảng giá yêu cầu',
    'Mã bảng giá cố định',
    'Mã bảng giá chứng từ',
    'Mã bảng giá hàng nhẹ',
    'Mã bảng giá hàng nặng ',
    'Giá khác',
    'Ngày bắt đầu',
    'Ngày kết thúc',
    'Phụ phí xăng dầu',
    'Tỷ giá (VNĐ)',
    'Tỷ lệ LKD/Giá bán gốc chưa phụ phí',
    'Ghi chú 1',
    'Ghi chú 2',
  ],
];

export const ExportContractColumnName = [
  [
    'Tình trạng khách hàng',
    'Mã khách hàng',
    'Tên khách hàng',
    'Ngày tạo',
    'Mã phụ lục hợp đồng',
    'Tên phụ lục hợp đồng',
    'Dịch vụ sử dụng',
    'Loại hợp đồng/ Loại phụ lục hợp đồng',
    'Lịch thanh toán công nợ kể từ ngày xuất hóa đơn',
    'Ngày bắt đầu',
    'Ngày kết thúc',
    'Thẩm định',
    'Nhân viên thẩm định',
    'Ghi chú',
  ],
];

export const ExportCustomerColumnName = [
  [
    'Tình trạng khách hàng',
    'Công ty quản lý khách hàng',
    'Thông tin đơn vị',
    'Nhóm khách hàng hoặc nhà cung cấp',
    'Thời gian tạo mã',
    'Mã khách hàng',
    'Tên khách hàng',
    'Tên khách hàng (Tiếng Anh)',
    'Địa chỉ chi tiết',
    'Địa chỉ chi tiết (Tiếng Anh)',
    'Phường/Xã',
    'Quận/Huyện',
    'Thành phố',
    'Quốc gia',
    'Mã định danh',
    'Người liên hệ',
    'Số điện thoại di động',
    'SĐT',
    'Mã vùng',
    'Email',
    'Loại khách hàng',
    'Dịch vụ',
    'Loại khách hàng vào mạng',
    'Mã bưu chính',
    'Ngày mở mã/ Active lại',
    'Ghi chú',
    'Nhân viên mở mã khách hàng',
    'Ngày tháng cập nhật mới nhất',
    'Nhân viên giao nhận',
    'Nhân viên quản lý khách hàng',
    'Ngày tháng cập nhật mới nhất',
    'Nhân viên kinh doanh được bàn giao',
    'Ngày tháng cập nhật mới nhất',
    'Nhân viên Dịch vụ khách hàng',
    'Nhân viên xuất hóa đơn',
    'Nhân viên thu nợ',
    'Quản lý kinh doanh cấp Tổ',
    'Quản lý kinh doanh cấp Phòng',
    'Quản lý kinh doanh cấp Miền',
  ],
];

export const ExportCustomerDetailColumnName = [
  [
    '',
    '',
    '',
    '1. Thông tin chung',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '2. Tài chính',
    '',
    '',
    '3. Thông tin gửi Bảng kê',
    '',
    '',
    '',
    '4. Thông tin gửi hóa đơn điện tử',
    '',
    '',
    '',
    '5. Thông tin thu nợ',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Tình trạng khách hàng',
    'Mã khách hàng',
    'Tên khách hàng',
    'Ngày Tháng nhập thông tin', // thong tin chung
    'Tên người thụ hưởng',
    'Chức vụ',
    'SĐT người thụ hưởng',
    'Người trực tiếp hưởng hay người thân',
    'Quan hệ với người thụ hưởng',
    'Số tài khoản thụ hưởng',
    'Ngân hàng thụ hưởng',
    'Ghi chú',
    'Loại thanh toán', // Tai chinh
    'Kỳ chốt cước',
    'Ghi chú',
    'Người liên hệ', // Thong tin gui bang ke
    'Danh sách mail gửi bảng kê tự động',
    'Số di động',
    'Ghi chú',
    'Người liên hệ', // Thong tin gui hoa don dien tu
    'Danh sách mail gửi hóa đơn tự động',
    'Số di động',
    'Ghi chú',
    'Người liên hệ', // Thong tin thu no
    'Email thu nợ',
    'Số điện thoại',
    'Số di động',
    'Địa chỉ thu nợ',
    'Ghi chú',
  ],
];
