import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1782378791435 implements MigrationInterface {
    name = 'Migrations1782378791435'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_a_links" DROP CONSTRAINT "FK_user_a_links_user"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_d9e7d00df7f1c673f3f31e2a927"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_ab430f09e3aeaf1901ec6925ca5"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_95c41f5279c57bda8eb21091191"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_6748d99b0f46b0cd6d9c12990ff"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "FK_7c3c817c18130658241e10f6313"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "FK_7055f445a3fe50004f21fdf88ea"`);
        await queryRunner.query(`ALTER TABLE "user_a_links" DROP CONSTRAINT "UQ_user_a_links_user_entity"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "booking" DROP COLUMN "partner_code_mapping"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP COLUMN "ales_price"`);
        await queryRunner.query(`CREATE TYPE "public"."user_a_links_a_target_enum" AS ENUM('mhvn', 'gp')`);
        await queryRunner.query(`ALTER TABLE "user_a_links" ADD "a_target" "public"."user_a_links_a_target_enum" NOT NULL DEFAULT 'mhvn'`);
        await queryRunner.query(`CREATE TYPE "public"."users_account_type_enum" AS ENUM('supplier', 'customer')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "account_type" "public"."users_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "region" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "files"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "files" character varying array`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "status" character varying NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "country" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "lkd_rate"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "lkd_rate" double precision`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_3" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trackings" ALTER COLUMN "latest_message" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ml_exchange_rates" DROP COLUMN "rate"`);
        await queryRunner.query(`ALTER TABLE "ml_exchange_rates" ADD "rate" integer NOT NULL`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "history_code_seq" OWNED BY "history"."code"`);
        await queryRunner.query(`ALTER TABLE "history" ALTER COLUMN "code" SET DEFAULT nextval('"history_code_seq"')`);
        await queryRunner.query(`ALTER TABLE "history" ALTER COLUMN "code" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "UQ_7c3c817c18130658241e10f6313" UNIQUE ("business_staff_id")`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "shareholder_equity_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "shareholder_equity_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_cost_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_cost_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "lkd_sales_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "lkd_sales_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_pp_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_pp_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_pp_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_pp_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_total_pp_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_total_pp_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_sales_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_sales_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_sales_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_sales_price" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "ppxd" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "ppxd" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_ppxd" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_ppxd" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_ppxd" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_ppxd" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_pp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_pp" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_gv_pp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_gv_pp" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_extend_gv_pp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_extend_gv_pp" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_shareholder_equity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_shareholder_equity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_gv_acf" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_gv_acf" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_permanent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_permanent" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_sales" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_sales" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "dividend_2_percent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "dividend_2_percent" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_for_business" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_for_business" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "bonus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "bonus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "remaining_profit" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "remaining_profit" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_vat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_vat" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "vat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "vat" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_vat" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_vat" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "UQ_7055f445a3fe50004f21fdf88ea" UNIQUE ("exchange_rate_id")`);
        await queryRunner.query(`ALTER TABLE "management_staff" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "management_staff" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "checkpoints" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "checkpoints" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "virtual_delivery_address_id_seq" OWNED BY "virtual_delivery_address"."id"`);
        await queryRunner.query(`ALTER TABLE "virtual_delivery_address" ALTER COLUMN "id" SET DEFAULT nextval('"virtual_delivery_address_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "virtual_delivery_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_user_a_links_user_target" ON "user_a_links" ("user_id", "a_target") `);
        await queryRunner.query(`ALTER TABLE "user_a_links" ADD CONSTRAINT "UQ_user_a_links_user_target_entity" UNIQUE ("user_id", "a_target", "link_type", "a_entity_id")`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_e85b7fa33d2203b4e6ec54f0950" FOREIGN KEY ("booking_id") REFERENCES "booking"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_6748d99b0f46b0cd6d9c12990ff" FOREIGN KEY ("sales_staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_ab430f09e3aeaf1901ec6925ca5" FOREIGN KEY ("checkin_staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_95c41f5279c57bda8eb21091191" FOREIGN KEY ("checkout_staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_d9e7d00df7f1c673f3f31e2a927" FOREIGN KEY ("manifest_staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_ee283c9adbadc5f1a2ff392eee5" FOREIGN KEY ("booking_id") REFERENCES "booking"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "FK_52005126d04209f8b5d8c156cc7" FOREIGN KEY ("booking_id") REFERENCES "booking"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "FK_7055f445a3fe50004f21fdf88ea" FOREIGN KEY ("exchange_rate_id") REFERENCES "ml_exchange_rates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "FK_7c3c817c18130658241e10f6313" FOREIGN KEY ("business_staff_id") REFERENCES "staffs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checkpoints" ADD CONSTRAINT "FK_5317ef54e5765a3c4fc02090b88" FOREIGN KEY ("tracking_id") REFERENCES "trackings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_detail" ADD CONSTRAINT "FK_9d653303b2704bb03eba7c71c8b" FOREIGN KEY ("booking_id") REFERENCES "booking"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "booking_detail" DROP CONSTRAINT "FK_9d653303b2704bb03eba7c71c8b"`);
        await queryRunner.query(`ALTER TABLE "checkpoints" DROP CONSTRAINT "FK_5317ef54e5765a3c4fc02090b88"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "FK_7c3c817c18130658241e10f6313"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "FK_7055f445a3fe50004f21fdf88ea"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "FK_52005126d04209f8b5d8c156cc7"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_ee283c9adbadc5f1a2ff392eee5"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_d9e7d00df7f1c673f3f31e2a927"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_95c41f5279c57bda8eb21091191"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_ab430f09e3aeaf1901ec6925ca5"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_6748d99b0f46b0cd6d9c12990ff"`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" DROP CONSTRAINT "FK_e85b7fa33d2203b4e6ec54f0950"`);
        await queryRunner.query(`ALTER TABLE "user_a_links" DROP CONSTRAINT "UQ_user_a_links_user_target_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_a_links_user_target"`);
        await queryRunner.query(`ALTER TABLE "virtual_delivery_address" ALTER COLUMN "id" SET DEFAULT nextval('virtual_delivery_address_id_seq1')`);
        await queryRunner.query(`ALTER TABLE "virtual_delivery_address" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "virtual_delivery_address_id_seq"`);
        await queryRunner.query(`ALTER TABLE "checkpoints" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "checkpoints" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "management_staff" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "management_staff" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "UQ_7055f445a3fe50004f21fdf88ea"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_vat" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_vat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "vat" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "vat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_vat" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_vat" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "remaining_profit" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "remaining_profit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "bonus" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "bonus" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_for_business" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_for_business" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "dividend_2_percent" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "dividend_2_percent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_sales" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_sales" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_permanent" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_permanent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_gv_acf" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_gv_acf" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_shareholder_equity" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_shareholder_equity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_extend_gv_pp" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_origin_extend_gv_pp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_gv_pp" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_gv_pp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_pp" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_extend_pp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_ppxd" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_ppxd" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_ppxd" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_ppxd" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "ppxd" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "ppxd" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_sales_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_sales_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_sales_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_sales_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_sales_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_total_pp_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_origin_total_pp_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_pp_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "gv_total_pp_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_pp_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "total_pp_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "lkd_sales_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "lkd_sales_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_cost_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "original_cost_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "shareholder_equity_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "shareholder_equity_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_price" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ALTER COLUMN "sales_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" DROP CONSTRAINT "UQ_7c3c817c18130658241e10f6313"`);
        await queryRunner.query(`ALTER TABLE "history" ALTER COLUMN "code" SET DEFAULT nextval('history_code_seq1')`);
        await queryRunner.query(`ALTER TABLE "history" ALTER COLUMN "code" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "history_code_seq"`);
        await queryRunner.query(`ALTER TABLE "ml_exchange_rates" DROP COLUMN "rate"`);
        await queryRunner.query(`ALTER TABLE "ml_exchange_rates" ADD "rate" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trackings" ALTER COLUMN "latest_message" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_3" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "receiver_address_1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "lkd_rate"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "lkd_rate" integer`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "country" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "status" "public"."customers_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "files"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "files" text array`);
        await queryRunner.query(`ALTER TABLE "staffs" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "staffs" ADD "region" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "account_type"`);
        await queryRunner.query(`DROP TYPE "public"."users_account_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user_a_links" DROP COLUMN "a_target"`);
        await queryRunner.query(`DROP TYPE "public"."user_a_links_a_target_enum"`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD "ales_price" numeric NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "booking" ADD "partner_code_mapping" character varying`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "state" character varying`);
        await queryRunner.query(`ALTER TABLE "user_a_links" ADD CONSTRAINT "UQ_user_a_links_user_entity" UNIQUE ("user_id", "link_type", "a_entity_id")`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "FK_7055f445a3fe50004f21fdf88ea" FOREIGN KEY ("exchange_rate_id") REFERENCES "ml_exchange_rates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finance_cpn" ADD CONSTRAINT "FK_7c3c817c18130658241e10f6313" FOREIGN KEY ("business_staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_6748d99b0f46b0cd6d9c12990ff" FOREIGN KEY ("sales_staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_95c41f5279c57bda8eb21091191" FOREIGN KEY ("checkout_staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_ab430f09e3aeaf1901ec6925ca5" FOREIGN KEY ("checkin_staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pu_deliveries" ADD CONSTRAINT "FK_d9e7d00df7f1c673f3f31e2a927" FOREIGN KEY ("manifest_staff_id") REFERENCES "staffs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_a_links" ADD CONSTRAINT "FK_user_a_links_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
